[build]
  base = "/"
  command = "npm run build"
  publish = "/dist/"
  functions = "netlify/functions"

[functions]
  directory = "functions/"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"